---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: python:3.7-alpine
    commands:
      - pip install --upgrade pip pipenv
      - pipenv install --dev
      - pipenv run flake8

---
kind: pipeline
type: docker
name: docs

steps:
  - name: build
    image: python:3.7-alpine
    commands:
      - pip install --upgrade pip pipenv
      - pipenv install --dev
      - pipenv run mkdocs build
  - name: publish
    image: plugins/gh-pages
    settings:
      username: jakew-bot
      password:
        from_secret: github_token
      pages_directory: site/

trigger:
  branch:
    - master
  event:
    - push