name: Generate Binaries
on: [push, pull_request]
jobs:
  bin_windows:
    name: Generate Windows Binaries
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
    - name: Generate binary
      run: python -m pipenv run pyinstaller -y --add-data "payloads;payloads/." -F centsecure.py
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: windows
        path: dist
  bin_linux:
    name: Generate Linux Binaries
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
    - name: Generate binary
      run: python -m pipenv run pyinstaller -y --add-data "payloads:payloads/." -F centsecure.py
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux
        path: dist
